# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 19:27
from __future__ import unicode_literals

import django.contrib.sites.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20160715_1404'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='site',
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
