# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [('filemetadata', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('version', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('schema', jsonfield.fields.JSONField()),
                ('description', models.TextField(blank=True)),
                ('contributor', models.CharField(default='Dataverse core', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
