# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filemetadata', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('datafile_id', models.IntegerField(default=1)),
                ('metadata', jsonfield.fields.JSONField()),
                ('published', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1, help_text='Placeholder')),
            ],
            options={
                'verbose_name': 'File metadata',
                'verbose_name_plural': 'File metadata',
                'ordering': ('schema', '-version'),
            },
        ),
        migrations.CreateModel(
            name='MetadataSchemaSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('1 - SUBMITTED', '1 - SUBMITTED'), ('2 - UNDER_REVIEW', '2 - UNDER_REVIEW'), ('3 - ACCEPTED', '3 - ACCEPTED'), ('4 - REJECTED', '4 - REJECTED')], default='1 - SUBMITTED', max_length=100)),
                ('contributor', models.CharField(default='Dataverse core', max_length=255)),
                ('review_complete', models.BooleanField(default=False)),
                ('version', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('schema', jsonfield.fields.JSONField()),
                ('description', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='metadataschema',
            options={'ordering': ('title', '-version')},
        ),
        migrations.AddField(
            model_name='metadataschema',
            name='dataverse_installation_id',
            field=models.CharField(default='harvard-dataverse', help_text='Used for namespacing schemas across installations. (Datatype not determined.)', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='metadataschema',
            unique_together=set([('title', 'version')]),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemetadata.MetadataSchema'),
        ),
        migrations.AlterUniqueTogether(
            name='filemetadata',
            unique_together=set([('schema', 'datafile_id', 'version')]),
        ),
    ]
